### ISSUE TITLE
Pergunta de iniciante na linguagem R

### ISSUE THREAD

**Issue by monteirosk** [courtsbr/esaj#10]
Estou com problemas na hora de instalar as dependências para rodar o projeto.

* installing to library ‘/Library/Frameworks/R.framework/Versions/3.3/Resources/library’
ERROR: dependencies ‘captchaTJSC’, ‘captchasaj’, ‘multidplyr’ are not available for package ‘esaj’
* removing ‘/Library/Frameworks/R.framework/Versions/3.3/Resources/library/esaj’

> install.packages("captchasaj")
Warning in install.packages :
  package ‘captchasaj’ is not available (for R version 3.3.2)

alguém pode me ajudar?

**Comment by jtrecenti** [comment]
esses pacotes não estão no CRAN (estão em fase bem inicial ainda)

para instalar, vc precisa usar o devtools

```
devtools::install_github('jtrecenti/captchasaj')
```
No futuro o captchasaj será transferido para a página github.com/decryptr
