### ISSUE TITLE
Major API change proposal

### ISSUE THREAD

**Issue by clente** [courtsbr/esaj#12]
### CJPG tables and files
- `cjpg_table()`
- **`browse_table()`**
- ~`cjpg()`~ **`download_cjpg()`**
- ~`cjpg_npags()`~
- ~`cjpg_parms()`~
- ~`cjpg_session()`~
- **`peek_cjpg()`**

### CJSG tables and files
- `cjsg_table()`
- ~`browse_cjsg()`~ **`browse_table()`**
- `download_cjsg()`
- `peek_cjsg()`

### Decisions
- `download_decision()`

### CPOPG and CPOSG
- `download_lawsuit()`
- ~`download_2deg_lawsuit()`~ **`download_lawsuit(degree = 2)`**

### Parsers
- ~`make_parser()`~ **`make_parser(type = "cposg")`**
- `parse_data()`
- `parse_movs()`
- `parse_parts()`
- `run_parser()`
- ~`parse_cjpg()`~ **`make_parser(type = "cjpg")`**
- ~`parse_cjsg()`~ **`make_parser(type = "cjsg")`**
- ~`parse_cpopg()`~ **`make_parser(type = "cpopg")`**

**Comment by jtrecenti** [comment]
Maybe

```
download_lawsuit(type = "sg") # or "pg"
```
