### ISSUE TITLE
download_2deg_lawsuit should be aware of list pages

### ISSUE THREAD

**Issue by azeloc** [courtsbr/esaj#13]
parsers won't work as intended on second degree docket numbers. sometimes one number defines two lawsuits.

```
wd <- tempdir()
downloaded_file <- esaj::download_2deg_lawsuit(id = '00000144420138260352', path = wd)

parser <- esaj::make_parser() %>% 
  esaj::parse_data()

run_parser(downloaded_file, parser, path = wd)
```

https://esaj.tjsp.jus.br/cposg/search.do?conversationId=&paginaConsulta=1&localPesquisa.cdLocal=-1&cbPesquisa=NUMPROC&tipoNuProcesso=SAJ&numeroDigitoAnoUnificado=&foroNumeroUnificado=&dePesquisaNuUnificado=&dePesquisa=00000144420138260352&uuidCaptcha=&pbEnviar=Pesquisar

`download_2deg_lawsuit` should download both lawsuits on such cases.

**Comment by clente** [comment]
Fixed with 12ac082a38ea9d233b77cfbd114f1e02b37aaa63
