### ISSUE TITLE
Falha ao instalar no R 3.4.4 no Windows

### ISSUE THREAD

**Issue by mgaldino** [courtsbr/esaj#22]
Rodei devtools::install_github("courtsbr/esaj") e recebi a seguinte mensagem de erro:

* installing *source* package 'esaj' ...
Warning in .write_description(db, file.path(outDir, "DESCRIPTION")) :
  Unknown encoding with non-ASCII data: converting to ASCII
Error in iconv(x[ind], "latin1", "ASCII", sub = "byte") : 
  objeto 'ind' nÃ£o encontrado
ERROR: installing package DESCRIPTION failed for package 'esaj'
* removing 'C:/Users/mgaldino/Documents/R/win-library/3.4/esaj'
In R CMD INSTALL

Meu "session Info":
R version 3.4.4 (2018-03-15)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

**Comment by clente** [comment]
[523fd60cd567c27aef0bd06b8caaa5c50b4116d5] Agora a descrição está inteira em ASCII. O erro deve deixar de ocorrer.
