### ISSUE TITLE
Write tests

### ISSUE THREAD

**Issue by jtrecenti** [courtsbr/esaj#6]
how?

**Comment by clente** [comment]
I'll try to implement something similar to what r-lib does in the `gh` package. If I interpreted this correctly, they change the tests if they identify that some resource is offline.

See: [https://github.com/r-lib/gh/tree/master/tests/testthat](https://github.com/r-lib/gh/tree/master/tests/testthat)

P.S.: As a way to get the tests up and running faster, I'll implement them using `testthat::skip_on_travis()` and `testthat::skip_on_appveyor()` so I'm able to run them locally but don't have to worry about errors while using CI

**Comment by clente** [comment]
Added tests for all refactored functions e97f2c180e7d1f442f94e3ed3be795242af6e690
